### GET REQUEST
GET http://localhost:8080/api/blogs/644201caa5edf12f5ba55249


### POST REQUEST
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

# {
#   "email": "john.dee@example.com",
#   "password": "password123"
# }

{
  "first_name": "Jodhn",
  "last_name": "Ddoe",
  "username": "tesdt12",
  "email": "testd.test1@gmail.com",
  "password": "password123",
  "looking_for_internship": true
}

### PUT REQUEST
PUT http://localhost:8080/blogs/6445cf6972601c03035c28e5
content-type: application/json

{
	"test": "world",
  "test_1": "You"
}

### DELETE REQUEST
DELETE http://localhost:8080/users/6446ebc8df8188a38c304569

Method: POST
URL: http://localhost:8080/api/auth/signup
Headers:




# http://localhost:8080/api/blogs
# Authorization: Bearer <your_JWT_token>

# {
#   "title": "My First Blog Post",
#   "content": "This is the content of my first blog post."
# }

# {
#   "email": "john.dee@example.com",
#   "password": "password123"
# }

